### ISSUE TITLE
Todo version 0.3

### ISSUE THREAD

**Issue by Bouke** [Bouke/django-two-factor-auth#17]
Wishlist:
- [x] #19 Mixin class for requiring OTP
- [x] #21 When requiring OTP, tell users to enable it (instead of redirecting to login view)
- [x] #18 - Optionally enforce OTP for admin views
- [x] #23 Investigate how to integrate with social logins (openid/oauth)
- [x] #22 Views documentation
- [x] #20 Include back button on backup tokens views
- [x] Allow a few days for translators to update translations
